name: Centralized Playwright Tests

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Select the test suite to run'
        required: true
        default: 'all'
        type: choice
        options:
          - 'all'
          - 'smoke'
          - 'example'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      run: |
        if [ "${{ github.event.inputs.test_suite }}" = "smoke" ]; then
          npx playwright test smokeTest.spec.ts
        elif [ "${{ github.event.inputs.test_suite }}" = "example" ]; then
          npx playwright test example.spec.ts
        else
          npx playwright test
        fi
      
    - name: Upload Test Report for the Team
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ github.event.inputs.test_suite }}
        path: playwright-report/
        retention-days: 30